on:
  push:
    branches:
      - master
      
jobs:
  build:    
    runs-on: ubuntu-latest
    steps:
      - name: build
      - uses: actions/checkout@v2                       
      - run: npm i
      - run: npm run build            
      
      - name: deploy
      - uses: Cecilapp/GitHub-Pages-deploy@master
