on:
  push:
    branches:
      - master
      
jobs:
  deploy:    
    runs-on: ubuntu-latest
    steps:      
      - uses: actions/checkout@v2
      - name: Setup Node.js environment       
        uses: actions/setup-node@v2.1.0    
        with:
          node-version: "12"      
      - run: npm install
        
      - name: Build
        uses: ./            
      - run: npm run-script build 
      
