on:
  push:
    branches:
      - master
      
jobs:
  main:    
    runs-on: ubuntu-latest
    steps:
      - name: build
        uses: actions/checkout@v2                       
      - run: npm i
      - run: npm run build            
      
      - name: deploy
        uses: Cecilapp/GitHub-Pages-deploy@master
        env:
          EMAIL: gabrielm.linassi@hotmail.com
          GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BUILD_DIR: build
