on:
  push:
    branches:
      - master
      
jobs:
  deploy:    
    runs-on: ubuntu-latest
    steps:      
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.0    
        with:
          node-version: "12"
      - run: npm install      
      - run: npm run develop
